name: photo_filter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # 폰트 설정 (옵션)
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: fonts/NotoSansKR-Regular.ttf
  #       - asset: fonts/NotoSansKR-Bold.ttf
  #         weight: 700 