name: photo_filter
description: 비즈니스 포토 - 소상공인 특화 필터 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # 폰트 설정 (옵션)
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: fonts/NotoSansKR-Regular.ttf
  #       - asset: fonts/NotoSansKR-Bold.ttf
  #         weight: 700 